default:
  tags:
    - k8s-ci-generic

stages:
    - test

python_tests:
    image: python:3.9
    stage: test
    script:
    - pip3 install pipenv
    - pipenv install
    - pipenv run pip3 install pytest
    - pipenv run python3 -m pytest